config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[index create new]
  devise_for :users
  root 'problems#index'

  resources :users, only: %i[show index]
  resources :followings, only: %i[destroy]

  get 'following/:id', to: 'followings#create', as: 'follow'
  resources :problems do
    resources :comments, only: %i[create]
    resources :likes, only: %i[create destroy]
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
  validates :body, presence: true, length: { maximum: 1000,
                                             too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user
  belongs_to :category
  has_rich_text :body
  scope :ordered_problem, -> { order(created_at: :desc).includes(:user) }
  scope :user_filter_problem, ->(user) { where(user: user) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /problems
  # GET /problems.json
  def index
    @problems = current_user.followeds_problems
    @problem = Problem.new
    @users_first_three = current_user.who_follow.last(3)
  end

  # GET /problems/1
  # GET /problems/1.json

  # GET /problems/new
  def new
    @problem = current_user.problems.build
  end

  # GET /problems/1/edit

  # POST /problems
  # POST /problems.json
  def create
    @problem = current_user.problems.build(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to root_path, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to root_path, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    if @problem
      @problem.destroy
      respond_to do |format|
        format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { render @problem }
      format.json { render json: @problem.errors, status: :unprocessable_entity }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_problem
    @problem = Problem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def problem_params
    params.require(:problem).permit(:user, :content, :user_id, :body, :category_id)
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_feed.html.erb
<div class="container d-flex justify-content-center border mt-2 mb-4 mx-0 rounded row align-middle shadow problems-form">
  <%= render 'form' %>
</div>
<div class='cont-problems'>
  <% @problems.each do |problem| %>
    <div class="container border py-4 my-5 mx-auto d-flex col-8 problems">
      
      <div class="col-4 userimg d-flex justify-content-center align-items-center">
        <%= user_avatar(problem.user) %>
      </div>

      <div class="col-8 problems-content">
        <div class='d-flex justify-content-between align-items-center'>
          <div>
            <strong><%= problem.user.fullname %></strong><br/>
            <small>@<%= problem.user.username %></small><br/>
          </div>
          <div class='like'>
            <%= like_or_dislike_btn(problem) %>
          </div>
        </div>
        <h5><%= problem.category.category%></h5>
        <%= problem.body %>

        <%= render partial: 'comments/comment', collection: problem.comments %>
        <%= form_for(problem.comments.new, url: problem_comments_path(problem)) do |form| %>
          <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
          <%= form.submit 'Comment', class: 'btn mt-2 comment' %>
        <% end %>
        <div class='d-flex justify-content-end'>
          <%= comment_settings(problem) %>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/problems/_form.html.erb
<%= form_with(model: @problem, local: true, html: {class: 'form-p'}) do |form| %>
  <div class="p-3 mr-3 trix">
    <div class='d-flex align-items-center title-fp'>
      <h3 class='mr-3 mb-3'>Category: </h3>
      <%= form.select :category_id, Category.all.map { |c| [c.category, c.id]} %>
    </div>
    <div class="text-area">
      <%= form.rich_text_area :body, label: "What's Your Problem", input_html: { class: "rich-text-input" }, wrapper: false, label_html: {class: "label"}, placeholders: "Your Problem...", autofocus: true %>
    </div>

    <%= hidden_field_tag(:redirect_url, root_path) %>
    <%= form.button :submit, class: "btn comment mt-3" %>
  </div>
<% end %>

app/views/problems/_left-side.html.erb
<section class='home-menu bg-left m-0'>
  <div class='user-profile d-flex justify-content-center'>
    <div class='user-photo'>
      <%= current_avatar %>
    </div>
    <div class='user-name d-flex justify-content-center align-items-center'>
      <h1 class='text-light'><%= current_user.fullname %></h1>
    </div>
  </div>
  <div class='followings d-flex justify-content-around'>
    <div class='followers text-center'>
      <h3 class='text-light'>Followers</h3>
      <h3 class='text-light'><%= current_user.followers.count.to_s %></h3>
    </div>
    <div class='followeds text-center'>
      <h3 class='text-light'>Followed</h3>
      <h3 class='text-light'><%= current_user.followeds.count.to_s %></h3>
    </div>
  </div>
  <div class='home-page'>
    <%= link_to root_path, class: 'd-flex justify-content-start align-items-center h-items' do%>
      <span><i class="fas fa-home text-light"></i></span> 
      <h3 class='m-0 text-light'> HOME</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to users_path, class: 'd-flex justify-content-start align-items-center h-items' do%>
      <span><i class="fas fa-at text-light"></i></span>
      <h3 class='m-0 text-light'> CONECT</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to categories_path, class: 'd-flex justify-content-start align-items-center h-items' do%>
      <span><i class="fab fa-slack-hash text-light"></i></span>
      <h3 class='m-0 text-light'> CATEGORIES</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to user_path(current_user.id), class: 'd-flex justify-content-start align-items-center h-items' do%>
      <span><i class="fas fa-user-alt text-light"></i></span>
      <h3 class='m-0 text-light'> PROFILE</h3>
    <% end%>
  </div>
</section>

app/views/problems/_navbar.html.erb
<nav class="navbar navbar-dark bg-navbar">
  <%= link_to root_path, class: 'd-flex align-items-center navbar-brand text-dark' do%>
    <span class='logo-navbar mx-2 text-light'><i class="fas fa-tools"></i></span>
    <h1 class="my-1 font-weight-bolder text-light">NO PROBLEM</h1>
  <% end %>
  <div class="d-flex justify-content-between align-items-center">
    <%= signed_in? %>
  </div>
</nav>

app/views/problems/_profile.html.erb
<section class='home-menu bg-secondary m-0'>
  <div class='user-profile'>
    <div class='user-photo'>
    </div>
    <div class='user-name'>
      <h1>Hola</h1>
    </div>
  </div>
  <div class='followings d-flex justify-content-around'>
    <div class='followers text-center'>
      <h3>Followers</h3>
      <p> 134</p>
    </div>
    <div class='followeds text-center'>
      <h3>Followeds</h3>
      <p> 100</p>
    </div>
  </div>
  <div class='home-page'>
    <%= link_to root_path, class: 'd-flex justify-content-center align-items-center' do%>
      <span><i class="fas fa-home"></i></span> 
      <h3 class='m-0'> HOME</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to root_path, class: 'd-flex justify-content-center align-items-center' do%>
      <span><i class="fas fa-at"></i></span>
      <h3 class='m-0'> CONECT</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to root_path, class: 'd-flex justify-content-center align-items-center' do%>
      <span><i class="fab fa-slack-hash"></i></span>
      <h3 class='m-0'> DISCOVER</h3>
    <% end%>
  </div>
  <div class='home-page text-center'>
    <%= link_to root_path, class: 'd-flex justify-content-center align-items-center' do%>
      <span><i class="fas fa-user-alt"></i></span>
      <h3 class='m-0'> PROFILE</h3>
    <% end%>
  </div>
</section>

app/views/problems/edit.html.erb
<section class='container-fluid p-0 m-0'>
  <div class='row m-0'>
    <div class='col-2 left-side p-0 m-0'>
      <%= render 'left-side' %>
    </div>
    <div class='col-10 p-0 m-0'>
      <%= flash_message %>
      <%= render 'problems/navbar' %>
      <div class='col-7 container mt-5 shadow-lg p-3 mb-5 bg-white rounded editing-p'>
        <h1>Editing Problem</h1>

        <%= render 'form', problem: @problem %>
        <div class='text-center'> 
          <%= link_to 'Back', problems_path, class:'btn bg-left text-light ml-3' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/problems/index.html.erb
<section class='container-fluid p-0 m-0'>
  <div class='row m-0'>
    <div class='col-2 left-side p-0 m-0'>
      <%= render 'left-side' %>
    </div>
    <div class='col-10 p-0 m-0'>
      <%= flash_message %>
      <%= render 'problems/navbar' %>
      <div class='row m-0'>
        <div class="col-8 mt-5">
          <%= render 'feed' %>
        </div>
        <div class="col-3 shadow p-3 mb-5 bg-white rounded mt-5 trending">
          <div class='whotofollow'>
            <div class='w-title'>
              <h3>WHO TO FOLLOW?</h3>
            </div>
            <div>
              <% @users_first_three.each do |p| %>
                <div class="col-12 users-to-f text-start">
                  <%= user_avatar(p) %>
                  <%=link_to p.fullname, user_path(id: p.id) %>
                  <hr>
                </div>
              <% end %>
            </div>
            <div class="text-muted pt-2 ">
              <h4 class="text-center">Trending</h4>
              <hr>
              <div class="container text-center">
                <h6>#RubyonRails</h6>
                <hr>
                <h6>#React</h6>
                <hr>
                <h6>#Hacks</h6>
                <hr>
                <h6>#Plumbing</h6>
                <hr>
                <h6>#Laws</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/problems/new.html.erb
<section class='container-fluid p-0 m-0'>
  <div class='row m-0'>
    <div class='col-2 left-side p-0 m-0'>
      <%= render 'left-side' %>
    </div>
    <div class='col-10 p-0 m-0'>
      <%= flash_message %>
      <%= render 'problems/navbar' %>
      <div class='container mt-5 shadow-lg p-3 mb-5 bg-white rounded new-problem'>
        <h1>New Problem</h1>
        <div class='new-form-p'>
          <%= render 'form', problem: @problem %>
        </div>
        <div class='text-center'>
          <%= link_to 'Back', problems_path, class: 'back btn' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @problem.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @problem.user_id %>
</p>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>