config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[index create new]
  devise_for :users
  root 'problems#index'

  resources :users, only: %i[show index]
  resources :followings, only: %i[destroy]

  get 'following/:id', to: 'followings#create', as: 'follow'
  resources :problems do
    resources :comments, only: %i[create]
    resources :likes, only: %i[create destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category, uniqueness: true
  validates :category, presence: true
  has_many :problems
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order('created_at DESC')
    cate = params[:cate]
    @problems = if !cate.nil?
                  Problem.where(category_id: cate).order('created_at DESC').includes(:user)
                else
                  Problem.all
                end
  end

  # GET /categories/1
  # GET /categories/1.json

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    category = Category.find(params[:id])
    if category
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { render @category }
      format.json { render json: @category.errors, status: :unprocessable_entity }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :category %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, class: 'btn bg-navbar text-light create' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<section class='container-fluid p-0 m-0'>
  <div class='row m-0'>
    <div class='col-2 left-side bg-secondary p-0 m-0'>
      <%= render 'problems/left-side' %>
    </div>
    <div class='col-10 p-0 m-0'>
      <%= flash_message %>
      <%= render 'problems/navbar' %>
      <div class='col-8 mx-auto p-5 d-flex flex-column align-items-center index-cate'>
        <div class='title-c d-flex justify-content-center align-items-center border-top border-bottom'>
          <h1>CATEGORIES</h1>
        </div>
        <div class='d-flex justify-content-between align-items-center '>
          <h2 class='mr-4'>¡Create Your Own CATEGORY!: </h2>
          <h2><%= link_to 'New Category', new_category_path, class: 'btn bg-navbar text-light my-3 new-c' %></h2>
        </div>
        
        <div class='categories d-flex justify-content-around'>
          <% @categories.each do |category| %>
            <h3 class='mr-2'><%= link_to category.category, categories_path(:cate => category.id),class: 'btn bg-left text-light each-c' %></h3>
          <% end %>
        </div>

        <div class='col-12 container-all-cat d-flex flex-wrap'>
          <% @problems.each do |problem| %>
            <div class="container border py-4 my-2 mx-auto d-flex col-8 problems-c">
              <div class="col-4 userimg d-flex justify-content-center align-items-center">
                <%= user_avatar(problem.user) %>
              </div>
              <div class="col-8 problems-c-content">
                <div class='d-flex justify-content-between align-items-center'>
                  <div>
                    <strong><%= problem.user.fullname %></strong>
                    <br/>
                    <br/>
                    <small>@<%= problem.user.username %></small>
                    <br/>
                    <br/>
                  </div>
                  <div class='like-c'>
                    <%= like_or_dislike_btn(problem) %>
                  </div>
                </div>
                  <h5><%= problem.category.category%></h5>
                  <%= problem.body %>
                  <%= render partial: 'comments/comment', collection: problem.comments %>
                  <%= form_for(problem.comments.new, url: problem_comments_path(problem)) do |form| %>
                    <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
                    <%= form.submit 'Comment', class: 'btn mt-2 comment' %>
                  <% end %>
                  <div class='d-flex justify-content-end'>
                    <%= comment_settings(problem) %>
                  </div>
              </div>
            </div>
          <% end %>
        </div>
        
      </div> 
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class='container-fluid p-0 m-0'>
  <div class='row m-0'>
    <div class='col-2 left-side bg-secondary p-0 m-0'>
      <%= render 'problems/left-side' %>
    </div>
    <div class='col-10 p-0 m-0'>
      <%= flash_message %>
      <%= render 'problems/navbar' %>
      <div class="col-5 container shadow-lg p-3 mb-5 bg-white rounded mt-5 new-cate px-3">
        <h1>New Category</h1>
        <%= render 'form', category: @category %>
        <%= link_to 'Back', categories_path, class: 'btn bg-left text-light' %>
      </div>
    </div>
  </div>
</section>